### ISSUE TITLE
Where can I get the information for each of the filetype?

### ISSUE THREAD

**Issue by jabnakar** [Atvaark/FoxTool#1]

**Comment by Atvaark** [comment]
That depends on the kind of information you are looking for.
Could you specify what you mean by _the_ information?

If you want to know which of the [classes](https://github.com/Atvaark/FoxTool/tree/master/FoxTool/Tpp/Classes) are used in which files, then just decompile the entire data_02 archive and use a text search.

If you want to know what the file extensions (FOX2, PARTS etc.) are used for, then you have research that yourself.

**Comment by jabnakar** [comment]
I actually meant the latter but those classes are informative too ,already using your tool, thank you :D

**Comment by Atvaark** [comment]
I took a short look at the files and came to this result:

| Extension | Content |
| --- | --- |
| BND | Graph Bounder Data |
| CLO | Sim Cloth Setting |
| DES | Destruction |
| EVF | Event |
| FOX2 | Scene |
| FSD | Facial Settings Data |
| LAD | Lip Adjust Data |
| PARTS | Model Description |
| PH | Physics Object Description |
| PHSD | Physics Sound Parameter |
| SDF | Sound Data File Info |
| SIM | Simulation Object |
| TGT | Geometry Target Description |
| VDP | Vehicle Driving Parameter |
| VEH | Vehicles |
| VFXLF | Visual Effects Lense Flare |
